language: objective-c
osx_image: xcode9.2
script:
  - set -o pipefail
  - xcodebuild -workspace "KeepInTouch.xcworkspace" -scheme "KeepInTouch" -sdk "iphonesimulator11.2" -destination "OS=11.2,name=iPhone 5S" -configuration Debug ONLY_ACTIVE_ARCH=NO test;