# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
  
use_frameworks!

target 'LentaSDK' do

  # Pods for LentaSDK
	pod 'SWXMLHash', '~> 4.0.0'
	pod ‘PromiseKit’, ‘~> 4.4’

  target 'LentaSDKTests' do
    inherit! :search_paths
	pod 'SWXMLHash', '~> 4.0.0'
	pod ‘PromiseKit’, ‘~> 4.4’
  end


end
